### PR TITLE
Milestone one

### PR DESCRIPTION
**Pull request by srizzuto**
This is data architecture documentation designed in Lucid, required for milestone 1 of the Social Media project of Microverse.

### CODE REVIEW

**Review by mke2111 — CHANGES_REQUESTED** [review]
# STATUS: CHANGES REQUIRED 🔴 ♻️ 

## Hey Happy Coders, 👋🏽 
**This is a great project you have going on, well-done lads**. 

### Well-done 💯 
    1. The ERD has the user and friendship table set 👍🏽 
    

**However, there are a few sections to improve before your project is approved.** 🔴 
<hr>

### REQUIRED

- [x] The standard format of writing PKs should be ID and not user_id. Give this a change and maintain the format for all your tables.
- [x] Enable the GitHub Actions in the Actions tab. This will activate the linter checks.
- [x] User table has image_link column ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone1/imglink.png) from Pathwright)
- [x] Add the missing tables along with the respective association.

   1. One User can create many Comments.
    2. One Comment is created by only One User.
    
    1. One User can create many Posts.
    2. One Post is created by only One User.

    1. One User can make many Likes.
    2. One Like is made by only One User.

    1. One Post can have many Likes.
    2. One Like is just for One Post.

    1. One Post can have many Comments.
    2. One Comment is just for One Post.

#

### Kindly make all the requested changes and submit another CRR. 💯 

**Cheers 🍹 and Happy coding 💻** 

<hr>

Mention @mke2111 in this thread and I'll be glad to help. 😄 
### Best regards
Slack 🆘  Roy Mukuye
Twitter 🐦  [Roy Mukuye](https://twitter.com/Roymkenya)
LinkedIn 🔗  [Roy Mukuye](https://www.linkedin.com/in/roy-mukuye/)

**Comment by barackm** [comment]
Hi @mke2111, I hope you are doing great, it seems that the requested changes on the associations are for the second milestone, for this first one it's all about Documentation (ERD) for the friendship feature.

**Comment by mke2111** [comment]
> Hi @mke2111, I hope you are doing great, it seems that the requested changes on the associations are for the second milestone, for this first one it's all about Documentation (ERD) for the friendship feature.

### The requested changes are supposed to be reflected on the ERD. You only have two tables (user and friendship tables). You need the comment, like, and post tables.
The associations will obviously be represented by the arrows linking your tables.

**Review by carlos-ssh — COMMENTED** [review]
Hello team!👋🏽
Good job!

**Review by carlos-ssh — APPROVED** [review]
**Status approved** ‼️ 🍾🍾🍾
Hello team!👋🏽
Good job!

Now you can merge and continue working in this nice project!

_Happy coding_
@Carlos-SSH

**Pull request merged**
